#!/bin/bash

if [ ${UID} -ne 0 ]
then
echo
echo "you need root access"
echo
exit
fi
## Check number of processors

if [ ${C} -eq 1 ] 
C=`nproc`
then 
     echo "This server is very small"
     exit 2
fi

