#!/bin/bash

if [ ${UID} -ne 0 ]
then
echo
echo "you need root access"
echo
exit
fi
## Check number of processors

if [ `nproc` -eq 1 ] 
then 
     echo "This server is very small"
     exit 2
fi

# Checking memory
free -m
exit o
